#!/bin/bash

## York Transcription to ELAN Tabbing Script
## Author: Naomi Cui, University of Toronto
##		  cui.naomi@gmail.com
##		  www.nowme.ca
## Version: 1.10
## Last updated: 9 October 2013
## Written and tested on Mac OS X Lion 10.7.5

MINARGS=1

tabber() {
	
	firstline=`head -1 $1`
	speaker1=${firstline:1:3}
	speaker2=${firstline:19:1}

	# Replace all Microsoft Word carriage returns
	# with Unix new line characters
	cat $1 | tr '' '\n' > linebreak_$1
	
	# Strip leading whitespace for each line
	cat linebreak_$1 | sed -e 's/^[ \t]*//' > cleanspace_$1

	rm linebreak_$1

	## For overlaps:
	## [A] Speech [B] Speech
	## [A] Continued speech. <= this line MUST begin with [A] again
	## or [B], depending on who is speaking
	
        # Insert middle of the line tabs
        cat cleanspace_$1 | sed -e "s/ \[$speaker1\]/           \[$speaker1\]/g" > awkready_$1

	fn=awkready_$1

	awk -v sp1="$speaker1" -v sp2="$speaker2" '
		{if (NR > 1) {		
			if (index($0, sp1)==2) { 
				tabbed=1;
				}
			if (tabbed) { 
				if (index($0, sp2)==2) {
					tabbed=0;
					}
				else { print "\t", $0; }
				}
			if (tabbed==0) {
				print $0;
				} 
			}
		}
		' $fn > tabbed_$1
	rm cleanspace_$1
	rm awkready_$1

	mv tabbed_$1 $newdir
}

# Check if argument is directory
if [ -d $1 ]; then
	cd $1
	mkdir tabbed_$1
	newdir=tabbed_$1
		for textfile in *.txt;
		do
			tabber "$textfile"
		done
else
# Else argument is only a single text file
	if [ ${1: -4} == ".txt" ]; then
		tabber "$1"
	fi
fi
